# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  

  - task: UseNode@1
    inputs:
      version: '18.2'  
    displayName: "Use Node.js"

  - script: |
      npm install
    displayName: "Install Dependencies"

  - script: |
      npm test
    displayName: "Run Tests"
    continueOnError: true  

  - script: |
      git config --global user.name "Azure DevOps Sync Bot"
      git config --global user.email "suyash.keshari@truinc.com"

      # Add GitHub as a remote repository
      git remote add github https://$(GITHUB_PAT)@github.com//Truin-kyash/Nodejs.git

      # Fetch latest from both Azure DevOps and GitHub
      git fetch origin
      git fetch github

      # Merge changes
      git merge origin/main --allow-unrelated-histories -m "Merge from Azure DevOps"

      # Push to GitHub
      git push github main
    displayName: "Sync Azure DevOps to GitHub"

  - script: |
      echo "Creating a Pull Request on GitHub..."
      gh pr create --repo Truin-kyash/Nodejs --head $BRANCH_NAME --base main --title "Auto Sync from Azure DevOps" --body "This PR syncs changes from Azure DevOps."
    env:
      GITHUB_TOKEN: 7zAL22PKCRRxSNeklOhTlDRJHVAV0HFNL8tOtMpSW2FrvahFtjfVJQQJ99BCACAAAAAAAAAAAAASAZDO2t3H
    displayName: "Create Pull Request on GitHub"