name: Sync GitHub to Azure DevOps

on:
  push:
    branches:
      - main  

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.2'  

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        continue-on-error: true  

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Sync Bot"
          git config --global user.email "suyashkeshari2001@gmail.com.com"

      - name: Push to Azure DevOps
        run: |
          git remote remove origin
          git remote add origin https://$(AZURE_PAT)@dev.azure.com/suyashkeshari20010558/Repository-Sync/_git/Repository-Sync

          git fetch azure
          git merge origin/main --allow-unrelated-histories -m "Merge from GitHub"
          git push azure main
        env:
          AZURE_PAT: 41bw9YwYvNhN1DTfbFV2JkIJuul4PhmgHJiBmzdx3sHzvShT9kDQJQQJ99BCACAAAAAAAAAAAAASAZDO1CBv
